package com.matez.wildnature.registry;

import com.matez.wildnature.Main;
import com.matez.wildnature.blocks.*;
import com.matez.wildnature.blocks.boundingboxes.*;
import com.matez.wildnature.lists.WNBlocks;
import com.matez.wildnature.blocks.ModelBlock;
import net.minecraft.block.Block;
import net.minecraft.block.SlimeBlock;
import net.minecraft.block.SoundType;
import net.minecraft.block.material.Material;
import net.minecraft.block.material.MaterialColor;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;
import net.minecraftforge.common.ToolType;

public class OtherRegistry {

    Block[] block;

    public OtherRegistry(){
        block = new Block[]{
                WNBlocks.GLOWING_CRYSTAL_BLUE = new GlowingCrystalBase(Block.Properties.create(Material.MISCELLANEOUS).doesNotBlockMovement().harvestTool(ToolType.PICKAXE),new Item.Properties().group(Main.WILDNATURE_UNDERGROUND_GROUP), Main.RegistryEvents.location("glowing_crystal_blue")),
                WNBlocks.GLOWING_CRYSTAL_ORANGE = new GlowingCrystalBase(Block.Properties.create(Material.MISCELLANEOUS).doesNotBlockMovement().harvestTool(ToolType.PICKAXE),new Item.Properties().group(Main.WILDNATURE_UNDERGROUND_GROUP), Main.RegistryEvents.location("glowing_crystal_orange")),
                WNBlocks.GLOWING_CRYSTAL_RED = new GlowingCrystalBase(Block.Properties.create(Material.MISCELLANEOUS).doesNotBlockMovement().harvestTool(ToolType.PICKAXE),new Item.Properties().group(Main.WILDNATURE_UNDERGROUND_GROUP), Main.RegistryEvents.location("glowing_crystal_red")),
                WNBlocks.GLOWING_CRYSTAL_PURPLE = new GlowingCrystalBase(Block.Properties.create(Material.MISCELLANEOUS).doesNotBlockMovement().harvestTool(ToolType.PICKAXE),new Item.Properties().group(Main.WILDNATURE_UNDERGROUND_GROUP), Main.RegistryEvents.location("glowing_crystal_purple")),
                WNBlocks.GLOWING_CRYSTAL_WHITE = new GlowingCrystalBase(Block.Properties.create(Material.MISCELLANEOUS).doesNotBlockMovement().harvestTool(ToolType.PICKAXE),new Item.Properties().group(Main.WILDNATURE_UNDERGROUND_GROUP), Main.RegistryEvents.location("glowing_crystal_white")),
                WNBlocks.PEBBLE = new PebbleBase(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).doesNotBlockMovement().hardnessAndResistance(1.2F,0.5F).harvestTool(ToolType.PICKAXE),new Item.Properties().group(Main.WILDNATURE_UNDERGROUND_GROUP), Main.RegistryEvents.location("pebble")),
                WNBlocks.STONE_SPIKE= new StoneSpikeBlock(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).doesNotBlockMovement(),new Item.Properties().group(Main.WILDNATURE_UNDERGROUND_GROUP), Main.RegistryEvents.location("stone_spike"),new StoneSpike()),
                //BlocksList.STONE_SPIKE_MEDIUM_A = new StoneSpikeBlock(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).doesNotBlockMovement(),new Item.Properties().group(WILDNATURE_UNDERGROUND_GROUP),location("stone_spike_medium_a"),new StoneSpike()),
                //BlocksList.STONE_SPIKE_MEDIUM_B = new StoneSpikeBlock(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).doesNotBlockMovement(),new Item.Properties().group(WILDNATURE_UNDERGROUND_GROUP),location("stone_spike_medium_b"),new StoneSpike()),
                //BlocksList.STONE_SPIKE_BIG_A = new StoneSpikeBlock(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).doesNotBlockMovement(),new Item.Properties().group(WILDNATURE_UNDERGROUND_GROUP),location("stone_spike_big_a"),new StoneSpike()),
                //BlocksList.STONE_SPIKE_BIG_B = new StoneSpikeBlock(Block.Properties.create(Material.ROCK).sound(SoundType.STONE).doesNotBlockMovement(),new Item.Properties().group(WILDNATURE_UNDERGROUND_GROUP),location("stone_spike_big_b"),new StoneSpike()),
                WNBlocks.GEYSER = new GeyserBlock(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.5F,6F).sound(SoundType.STONE),new Item.Properties().group(Main.WILDNATURE_GROUP), Main.RegistryEvents.location("geyser")),

                WNBlocks.RS_DELAY = new RSDelayBlock(Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(0F).sound(SoundType.WOOD),new Item.Properties().group(ItemGroup.REDSTONE), Main.RegistryEvents.location("rs_delay")),
                WNBlocks.RS_PULSAR = new RSPulsarBlock(Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(0F).sound(SoundType.WOOD),new Item.Properties().group(ItemGroup.REDSTONE), Main.RegistryEvents.location("rs_pulsar")),
                WNBlocks.RS_PROXIMITY_SENSOR = new RSProximitySensorBlock(Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(0F).sound(SoundType.WOOD),new Item.Properties().group(ItemGroup.REDSTONE), Main.RegistryEvents.location("rs_proximity_sensor")),
                WNBlocks.RS_SIGNAL_HOLDER = new RSSignalHolder(Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(0F).sound(SoundType.WOOD),new Item.Properties().group(ItemGroup.REDSTONE), Main.RegistryEvents.location("rs_signal_holder")),
                WNBlocks.RS_GATE_AND = new RSAndGate(Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(0F).sound(SoundType.WOOD),new Item.Properties().group(ItemGroup.REDSTONE), Main.RegistryEvents.location("rs_gate_and")),

                WNBlocks.DUNGEON_LEVER = new LeverBase(Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(0.5F).sound(SoundType.LANTERN),new Item.Properties().group(ItemGroup.REDSTONE), Main.RegistryEvents.location("dungeon_lever")),
                WNBlocks.DUNGEON_REDSTONE_TORCH = new RedstoneTorchBase(Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(0F).sound(SoundType.LANTERN).lightValue(6), Main.RegistryEvents.location("dungeon_redstone_torch")),
                WNBlocks.DUNGEON_REDSTONE_TORCH_WALL = new RedstoneTorchWallBase(Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(0F).sound(SoundType.LANTERN).lightValue(6), Main.RegistryEvents.location("dungeon_redstone_torch_wall")),
                WNBlocks.RS_PISTON1 = new CustomPistonBlock(true,Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(0F).sound(SoundType.WOOD), Main.RegistryEvents.location("rs_piston1"), Main.RegistryEvents.location("rs_piston1_head"), Main.RegistryEvents.location("rs_piston1_moving")),
                WNBlocks.RS_PISTON1_HEAD = new CustomPistonHeadBlock(Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(0F).sound(SoundType.WOOD), Main.RegistryEvents.location("rs_piston1_head"), Main.RegistryEvents.location("rs_piston1"), Main.RegistryEvents.location("rs_piston1_moving")),
                WNBlocks.RS_PISTON1_MOVING = new CustomMovingPistonBlock(Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(0F).sound(SoundType.WOOD), Main.RegistryEvents.location("rs_piston1_moving")),
                WNBlocks.RS_DISPENSER = new BlockBase(Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(3F).sound(SoundType.STONE),new Item.Properties().group(ItemGroup.REDSTONE), Main.RegistryEvents.location("rs_dispenser")),
                WNBlocks.DUNGEON_COMMANDER = new DungeonCommander(Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(3F).sound(SoundType.STONE),new Item.Properties().group(ItemGroup.REDSTONE), Main.RegistryEvents.location("dungeon_commander")),
                WNBlocks.STEAM_GENERATOR = new SteamGeneratorBlock(Block.Properties.create(Material.IRON).hardnessAndResistance(5F,6F).sound(SoundType.METAL),new Item.Properties().group(ItemGroup.REDSTONE), Main.RegistryEvents.location("rs_steam_generator")),
                WNBlocks.STEAM_GENERATOR2 = new SteamGeneratorBlock2(Block.Properties.create(Material.IRON).hardnessAndResistance(5F,6F).sound(SoundType.METAL),new Item.Properties().group(ItemGroup.REDSTONE), Main.RegistryEvents.location("rs_steam_generator2")),


                WNBlocks.DUNGEON_HEART = new DungeonHeart(Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(10,100F).sound(SoundType.STONE).harvestTool(ToolType.PICKAXE),new Item.Properties().group(Main.WILDNATURE_UNDERGROUND_GROUP), Main.RegistryEvents.location("dungeon_heart")),
                WNBlocks.DUNGEON_TORCH = new TorchBase(Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(0F).sound(SoundType.LANTERN).lightValue(12), Main.RegistryEvents.location("dungeon_torch")),
                WNBlocks.DUNGEON_TORCH_WALL = new TorchWallBase(Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(0F).sound(SoundType.LANTERN).lightValue(12), Main.RegistryEvents.location("dungeon_torch_wall")),
                WNBlocks.CRYSTAL_TORCH = new CrystalTorch(Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(0F).sound(SoundType.LANTERN).lightValue(15), Main.RegistryEvents.location("crystal_torch")),
                WNBlocks.CRYSTAL_TORCH_WALL = new CrystalWallTorch(Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(0F).sound(SoundType.LANTERN).lightValue(15), Main.RegistryEvents.location("crystal_torch_wall")),

                WNBlocks.UNTIED_STRAWBALE = new BlockBase(Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("untied_strawbale")),
                WNBlocks.UNTIED_STRAWBALE_SLAB = new SlabBase(Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("untied_strawbale_slab")),
                WNBlocks.UNTIED_STRAWBALE_STAIRS = new StairsBase(WNBlocks.UNTIED_STRAWBALE.getDefaultState(),Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("untied_strawbale_stairs")),

                WNBlocks.STRAWBALE = new BlockBase(Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("strawbale")),
                WNBlocks.STRAWBALE_SLAB = new SlabBase(Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("strawbale_slab")),
                WNBlocks.STRAWBALE_STAIRS = new StairsBase(WNBlocks.STRAWBALE.getDefaultState(),Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("strawbale_stairs")),

                WNBlocks.STRAWBALE_AGED = new BlockBase(Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("strawbale_aged")),
                WNBlocks.STRAWBALE_AGED_SLAB = new SlabBase(Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("strawbale_aged_slab")),
                WNBlocks.STRAWBALE_AGED_STAIRS = new StairsBase(WNBlocks.STRAWBALE_AGED.getDefaultState(),Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("strawbale_aged_stairs")),

                WNBlocks.STRAWBALE_AGED_BROWN = new BlockBase(Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("strawbale_aged_brown")),
                WNBlocks.STRAWBALE_AGED_BROWN_SLAB = new SlabBase(Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("strawbale_aged_brown_slab")),
                WNBlocks.STRAWBALE_AGED_BROWN_STAIRS = new StairsBase(WNBlocks.STRAWBALE_AGED_BROWN.getDefaultState(),Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("strawbale_aged_brown_stairs")),

                WNBlocks.STRAWBALE_OLD = new BlockBase(Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("strawbale_old")),
                WNBlocks.STRAWBALE_OLD_SLAB = new SlabBase(Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("strawbale_old_slab")),
                WNBlocks.STRAWBALE_OLD_STAIRS = new StairsBase(WNBlocks.STRAWBALE_OLD.getDefaultState(),Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("strawbale_old_stairs")),

                WNBlocks.STRAWBALE_OLD_BROWN = new BlockBase(Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("strawbale_old_brown")),
                WNBlocks.STRAWBALE_OLD_BROWN_SLAB = new SlabBase(Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("strawbale_old_brown_slab")),
                WNBlocks.STRAWBALE_OLD_BROWN_STAIRS = new StairsBase(WNBlocks.STRAWBALE_OLD_BROWN.getDefaultState(),Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("strawbale_old_brown_stairs")),

                WNBlocks.BONES_BLOCK = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F).sound(SoundType.STONE),new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("bones_block")),

                WNBlocks.STONE_LAMP = new LampBase(Block.Properties.create(Material.ROCK).lightValue(15).hardnessAndResistance(1.3F).sound(SoundType.STONE),new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("stone_lamp")),
                WNBlocks.MOSSY_STONE_LAMP = new LampBase(Block.Properties.create(Material.ROCK).lightValue(15).hardnessAndResistance(1.3F).sound(SoundType.STONE),new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("mossy_stone_lamp")),
                WNBlocks.VILLAGE_LAMP = new LampBase(Block.Properties.create(Material.MISCELLANEOUS).lightValue(15).hardnessAndResistance(0.3F).sound(SoundType.GLASS),new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("village_lamp")),

                WNBlocks.STONE_CHANDELIER = new ChandelierBase(Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(2.3F,1F).sound(SoundType.STONE).lightValue(15),new Item.Properties(), Main.RegistryEvents.location("chandelier_stone")),
                WNBlocks.WOODEN_CHANDELIER = new ChandelierBase(Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(2F,0.6F).sound(SoundType.WOOD).lightValue(15),new Item.Properties(), Main.RegistryEvents.location("chandelier_wooden")),
                WNBlocks.CRYSTAL_CHANDELIER = new ChandelierBase(Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(1.8F,0.4F).sound(SoundType.GLASS).lightValue(15),new Item.Properties(), Main.RegistryEvents.location("chandelier_crystal")),
                WNBlocks.CANDLE = new CandleBase(Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(0.4F,0.2F).sound(SoundType.STONE).lightValue(10),new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("candle")),
                WNBlocks.LIGHTNING_BUG = new LightningBugBlock(Block.Properties.create(Material.ORGANIC).hardnessAndResistance(0.1F,0F).doesNotBlockMovement().sound(SoundType.SWEET_BERRY_BUSH).lightValue(5),new Item.Properties().group(Main.WILDNATURE_GROUP), Main.RegistryEvents.location("lightning_bug")),
                WNBlocks.GLOWSHROOM_LANTERN = new ShroomLantern(Block.Properties.create(Material.IRON).hardnessAndResistance(3.5F).sound(SoundType.LANTERN).lightValue(10),new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("glowshroom_lantern")),
                WNBlocks.ICESHROOM_LANTERN = new ShroomLantern(Block.Properties.create(Material.IRON).hardnessAndResistance(3.5F).sound(SoundType.LANTERN).lightValue(10),new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("iceshroom_lantern")),

                WNBlocks.ANDIRONS = new ModelBlock(Block.Properties.create(Material.IRON).sound(SoundType.ANVIL).hardnessAndResistance(2F,0.6F).harvestTool(ToolType.PICKAXE),new Item.Properties(), Main.RegistryEvents.location("andirons"),false, new AndironsBB()),
                WNBlocks.ANVIL = new ModelBlock(Block.Properties.create(Material.IRON).sound(SoundType.ANVIL).hardnessAndResistance(3F,3F).harvestTool(ToolType.PICKAXE),new Item.Properties(), Main.RegistryEvents.location("anvil"),false, new AnvilBB()),
                WNBlocks.CHAIR = new ModelBlock(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(0.6F,0.2F).harvestTool(ToolType.AXE),new Item.Properties(), Main.RegistryEvents.location("chair"),false, new ChairBB()),
                WNBlocks.HALFTABLE = new ModelBlock(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(0.6F,0.2F).harvestTool(ToolType.AXE),new Item.Properties(), Main.RegistryEvents.location("halftable"),false, new HalfTableBB()),
                WNBlocks.HANGINGSHELF = new ModelBlock(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(0.6F,0.2F).harvestTool(ToolType.AXE),new Item.Properties(), Main.RegistryEvents.location("hangingshelf"),true, new HangingShelfBB()),
                WNBlocks.SHELF = new ModelBlock(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(0.6F,0.2F).harvestTool(ToolType.AXE),new Item.Properties(), Main.RegistryEvents.location("shelf"),true, new ShelfBB()),
                WNBlocks.SMALLTABLE = new ModelBlock(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(0.6F,0.2F).harvestTool(ToolType.AXE),new Item.Properties(), Main.RegistryEvents.location("smalltable"),false, new SmallTableBB()),
                WNBlocks.STOOL = new ModelBlock(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(0.6F,0.2F).harvestTool(ToolType.AXE),new Item.Properties(), Main.RegistryEvents.location("stool"),false, new StoolBB()),
                WNBlocks.WEAPONSRACK = new ModelBlock(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(0.6F,0.2F).harvestTool(ToolType.AXE),new Item.Properties(), Main.RegistryEvents.location("weaponsrack"),false, new WeaponsRackBB()),

                //FURNITURES
                WNBlocks.OAK_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("oak_bench")),
                WNBlocks.SPRUCE_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("spruce_bench")),
                WNBlocks.BIRCH_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("birch_bench")),
                WNBlocks.JUNGLE_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("jungle_bench")),
                WNBlocks.ACACIA_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("acacia_bench")),
                WNBlocks.DARK_OAK_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("dark_oak_bench")),
                WNBlocks.ROSACEAE_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("rosaceae_bench")),
                WNBlocks.BAOBAB_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("baobab_bench")),
                WNBlocks.BEECH_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("beech_bench")),
                WNBlocks.CEDAR_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("cedar_bench")),
                WNBlocks.CHERRY_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("cherry_bench")),
                WNBlocks.CITRUS_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("citrus_bench")),
                WNBlocks.EBONY_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("ebony_bench")),
                WNBlocks.EUCALYPTUS_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("eucalyptus_bench")),
                WNBlocks.JACARANDA_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("jacaranda_bench")),
                WNBlocks.LARCH_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("larch_bench")),
                WNBlocks.MAHOGANY_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("mahogany_bench")),
                WNBlocks.MANGROVE_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("mangrove_bench")),
                WNBlocks.MAPLE_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("maple_bench")),
                WNBlocks.PALM_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("palm_bench")),
                WNBlocks.PLUM_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("plum_bench")),
                WNBlocks.REDWOOD_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("redwood_bench")),
                WNBlocks.WILLOW_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("willow_bench")),
                WNBlocks.GLOWING_CAVE_OAK_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("glowing_cave_oak_bench")),

                WNBlocks.OAK_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("oak_chair")),
                WNBlocks.SPRUCE_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("spruce_chair")),
                WNBlocks.BIRCH_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("birch_chair")),
                WNBlocks.JUNGLE_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("jungle_chair")),
                WNBlocks.ACACIA_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("acacia_chair")),
                WNBlocks.DARK_OAK_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("dark_oak_chair")),
                WNBlocks.ROSACEAE_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("rosaceae_chair")),
                WNBlocks.BAOBAB_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("baobab_chair")),
                WNBlocks.BEECH_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("beech_chair")),
                WNBlocks.CEDAR_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("cedar_chair")),
                WNBlocks.CHERRY_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("cherry_chair")),
                WNBlocks.CITRUS_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("citrus_chair")),
                WNBlocks.EBONY_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("ebony_chair")),
                WNBlocks.EUCALYPTUS_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("eucalyptus_chair")),
                WNBlocks.JACARANDA_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("jacaranda_chair")),
                WNBlocks.LARCH_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("larch_chair")),
                WNBlocks.MAHOGANY_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("mahogany_chair")),
                WNBlocks.MANGROVE_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("mangrove_chair")),
                WNBlocks.MAPLE_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("maple_chair")),
                WNBlocks.PALM_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("palm_chair")),
                WNBlocks.PLUM_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("plum_chair")),
                WNBlocks.REDWOOD_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("redwood_chair")),
                WNBlocks.WILLOW_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("willow_chair")),
                WNBlocks.GLOWING_CAVE_OAK_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("glowing_cave_oak_chair")),

                WNBlocks.OAK_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("oak_round_table")),
                WNBlocks.SPRUCE_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("spruce_round_table")),
                WNBlocks.BIRCH_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("birch_round_table")),
                WNBlocks.JUNGLE_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("jungle_round_table")),
                WNBlocks.ACACIA_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("acacia_round_table")),
                WNBlocks.DARK_OAK_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("dark_oak_round_table")),
                WNBlocks.ROSACEAE_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("rosaceae_round_table")),
                WNBlocks.BAOBAB_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("baobab_round_table")),
                WNBlocks.BEECH_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("beech_round_table")),
                WNBlocks.CEDAR_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("cedar_round_table")),
                WNBlocks.CHERRY_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("cherry_round_table")),
                WNBlocks.CITRUS_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("citrus_round_table")),
                WNBlocks.EBONY_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("ebony_round_table")),
                WNBlocks.EUCALYPTUS_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("eucalyptus_round_table")),
                WNBlocks.JACARANDA_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("jacaranda_round_table")),
                WNBlocks.LARCH_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("larch_round_table")),
                WNBlocks.MAHOGANY_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("mahogany_round_table")),
                WNBlocks.MANGROVE_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("mangrove_round_table")),
                WNBlocks.MAPLE_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("maple_round_table")),
                WNBlocks.PALM_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("palm_round_table")),
                WNBlocks.PLUM_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("plum_round_table")),
                WNBlocks.REDWOOD_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("redwood_round_table")),
                WNBlocks.WILLOW_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("willow_round_table")),
                WNBlocks.GLOWING_CAVE_OAK_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("glowing_cave_oak_round_table")),

                WNBlocks.OAK_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("oak_square_table")),
                WNBlocks.SPRUCE_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("spruce_square_table")),
                WNBlocks.BIRCH_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("birch_square_table")),
                WNBlocks.JUNGLE_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("jungle_square_table")),
                WNBlocks.ACACIA_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("acacia_square_table")),
                WNBlocks.DARK_OAK_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("dark_oak_square_table")),
                WNBlocks.ROSACEAE_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("rosaceae_square_table")),
                WNBlocks.BAOBAB_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("baobab_square_table")),
                WNBlocks.BEECH_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("beech_square_table")),
                WNBlocks.CEDAR_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("cedar_square_table")),
                WNBlocks.CHERRY_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("cherry_square_table")),
                WNBlocks.CITRUS_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("citrus_square_table")),
                WNBlocks.EBONY_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("ebony_square_table")),
                WNBlocks.EUCALYPTUS_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("eucalyptus_square_table")),
                WNBlocks.JACARANDA_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("jacaranda_square_table")),
                WNBlocks.LARCH_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("larch_square_table")),
                WNBlocks.MAHOGANY_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("mahogany_square_table")),
                WNBlocks.MANGROVE_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("mangrove_square_table")),
                WNBlocks.MAPLE_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("maple_square_table")),
                WNBlocks.PALM_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("palm_square_table")),
                WNBlocks.PLUM_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("plum_square_table")),
                WNBlocks.REDWOOD_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("redwood_square_table")),
                WNBlocks.WILLOW_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("willow_square_table")),
                WNBlocks.GLOWING_CAVE_OAK_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("glowing_cave_oak_square_table")),

                WNBlocks.OAK_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("oak_stool")),
                WNBlocks.SPRUCE_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("spruce_stool")),
                WNBlocks.BIRCH_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("birch_stool")),
                WNBlocks.JUNGLE_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("jungle_stool")),
                WNBlocks.ACACIA_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("acacia_stool")),
                WNBlocks.DARK_OAK_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("dark_oak_stool")),
                WNBlocks.ROSACEAE_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("rosaceae_stool")),
                WNBlocks.BAOBAB_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("baobab_stool")),
                WNBlocks.BEECH_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("beech_stool")),
                WNBlocks.CEDAR_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("cedar_stool")),
                WNBlocks.CHERRY_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("cherry_stool")),
                WNBlocks.CITRUS_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("citrus_stool")),
                WNBlocks.EBONY_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("ebony_stool")),
                WNBlocks.EUCALYPTUS_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("eucalyptus_stool")),
                WNBlocks.JACARANDA_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("jacaranda_stool")),
                WNBlocks.LARCH_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("larch_stool")),
                WNBlocks.MAHOGANY_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("mahogany_stool")),
                WNBlocks.MANGROVE_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("mangrove_stool")),
                WNBlocks.MAPLE_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("maple_stool")),
                WNBlocks.PALM_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("palm_stool")),
                WNBlocks.PLUM_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("plum_stool")),
                WNBlocks.REDWOOD_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("redwood_stool")),
                WNBlocks.WILLOW_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("willow_stool")),
                WNBlocks.GLOWING_CAVE_OAK_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("glowing_cave_oak_stool")),

                //END
                WNBlocks.STONE_FIREPIT = new CampfireBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F).lightValue(15).tickRandomly(), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("stone_firepit")),
                WNBlocks.GRANITE_FIREPIT = new CampfireBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F).lightValue(15).tickRandomly(), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("granite_firepit")),
                WNBlocks.DIORITE_FIREPIT = new CampfireBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F).lightValue(15).tickRandomly(), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("diorite_firepit")),
                WNBlocks.ANDESITE_FIREPIT = new CampfireBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F).lightValue(15).tickRandomly(), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("andesite_firepit")),

                WNBlocks.BASALT_FIREPIT = new CampfireBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F).lightValue(15).tickRandomly(), new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("basalt_firepit")),
                WNBlocks.CONGLOMERATE_FIREPIT = new CampfireBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F).lightValue(15).tickRandomly(),new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("conglomerate_firepit")),
                WNBlocks.GNEISS_FIREPIT = new CampfireBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F).lightValue(15).tickRandomly(),new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("gneiss_firepit")),
                WNBlocks.LIMESTONE_FIREPIT = new CampfireBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F).lightValue(15).tickRandomly(),new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("limestone_firepit")),
                WNBlocks.MARBLE_FIREPIT = new CampfireBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F).lightValue(15).tickRandomly(),new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("marble_firepit")),
                WNBlocks.PEGMATITE_FIREPIT = new CampfireBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F).lightValue(15).tickRandomly(),new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("pegmatite_firepit")),
                WNBlocks.SLATE_FIREPIT = new CampfireBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F, 4.5F).lightValue(15).tickRandomly(),new Item.Properties().group(Main.WILDNATURE_DECO_GROUP), Main.RegistryEvents.location("slate_firepit")),


                WNBlocks.BLACK_CURRANT_CAKE = new CakeBase(Block.Properties.create(Material.CAKE).hardnessAndResistance(0.5F).sound(SoundType.CLOTH),new Item.Properties().group(ItemGroup.FOOD), Main.RegistryEvents.location("black_currant_cake")),
                WNBlocks.CANDY_CAKE = new CakeBase(Block.Properties.create(Material.CAKE).hardnessAndResistance(0.5F).sound(SoundType.CLOTH),new Item.Properties().group(ItemGroup.FOOD), Main.RegistryEvents.location("candy_cake")),
                WNBlocks.CARROT_CAKE = new CakeBase(Block.Properties.create(Material.CAKE).hardnessAndResistance(0.5F).sound(SoundType.CLOTH),new Item.Properties().group(ItemGroup.FOOD), Main.RegistryEvents.location("carrot_cake")),
                WNBlocks.CHERRY_CAKE = new CakeBase(Block.Properties.create(Material.CAKE).hardnessAndResistance(0.5F).sound(SoundType.CLOTH),new Item.Properties().group(ItemGroup.FOOD), Main.RegistryEvents.location("cherry_cake")),
                WNBlocks.CHOCO_CAKE = new CakeBase(Block.Properties.create(Material.CAKE).hardnessAndResistance(0.5F).sound(SoundType.CLOTH),new Item.Properties().group(ItemGroup.FOOD), Main.RegistryEvents.location("choco_cake")),
                WNBlocks.CHOKEBERRY_CAKE = new CakeBase(Block.Properties.create(Material.CAKE).hardnessAndResistance(0.5F).sound(SoundType.CLOTH),new Item.Properties().group(ItemGroup.FOOD), Main.RegistryEvents.location("chokeberry_cake")),
                WNBlocks.DARK_CHOCOLATE_CAKE = new CakeBase(Block.Properties.create(Material.CAKE).hardnessAndResistance(0.5F).sound(SoundType.CLOTH),new Item.Properties().group(ItemGroup.FOOD), Main.RegistryEvents.location("dark_chocolate_cake")),
                WNBlocks.GRAPEFRUIT_CAKE = new CakeBase(Block.Properties.create(Material.CAKE).hardnessAndResistance(0.5F).sound(SoundType.CLOTH),new Item.Properties().group(ItemGroup.FOOD), Main.RegistryEvents.location("grapefruit_cake")),
                WNBlocks.HAWTHORN_CAKE = new CakeBase(Block.Properties.create(Material.CAKE).hardnessAndResistance(0.5F).sound(SoundType.CLOTH),new Item.Properties().group(ItemGroup.FOOD), Main.RegistryEvents.location("hawthorn_cake")),
                WNBlocks.KAMCHATKA_CAKE = new CakeBase(Block.Properties.create(Material.CAKE).hardnessAndResistance(0.5F).sound(SoundType.CLOTH),new Item.Properties().group(ItemGroup.FOOD), Main.RegistryEvents.location("kamchatka_cake")),
                WNBlocks.LEMON_CAKE = new CakeBase(Block.Properties.create(Material.CAKE).hardnessAndResistance(0.5F).sound(SoundType.CLOTH),new Item.Properties().group(ItemGroup.FOOD), Main.RegistryEvents.location("lemon_cake")),
                WNBlocks.MAZUREK = new CakeBase(Block.Properties.create(Material.CAKE).hardnessAndResistance(0.5F).sound(SoundType.CLOTH),new Item.Properties().group(ItemGroup.FOOD), Main.RegistryEvents.location("mazurek")),
                WNBlocks.MILK_CHOCOLATE_CAKE = new CakeBase(Block.Properties.create(Material.CAKE).hardnessAndResistance(0.5F).sound(SoundType.CLOTH),new Item.Properties().group(ItemGroup.FOOD), Main.RegistryEvents.location("milk_chocolate_cake")),
                WNBlocks.MINT_GOOSEBERRY_CAKE = new CakeBase(Block.Properties.create(Material.CAKE).hardnessAndResistance(0.5F).sound(SoundType.CLOTH),new Item.Properties().group(ItemGroup.FOOD), Main.RegistryEvents.location("mint_gooseberry_cake")),
                WNBlocks.ORANGE_CAKE = new CakeBase(Block.Properties.create(Material.CAKE).hardnessAndResistance(0.5F).sound(SoundType.CLOTH),new Item.Properties().group(ItemGroup.FOOD), Main.RegistryEvents.location("orange_cake")),
                WNBlocks.PINEAPPLE_CAKE = new CakeBase(Block.Properties.create(Material.CAKE).hardnessAndResistance(0.5F).sound(SoundType.CLOTH),new Item.Properties().group(ItemGroup.FOOD), Main.RegistryEvents.location("pineapple_cake")),
                WNBlocks.QUINCE_CAKE = new CakeBase(Block.Properties.create(Material.CAKE).hardnessAndResistance(0.5F).sound(SoundType.CLOTH),new Item.Properties().group(ItemGroup.FOOD), Main.RegistryEvents.location("quince_cake")),
                WNBlocks.RASPBERRY_CAKE = new CakeBase(Block.Properties.create(Material.CAKE).hardnessAndResistance(0.5F).sound(SoundType.CLOTH),new Item.Properties().group(ItemGroup.FOOD), Main.RegistryEvents.location("raspberry_cake")),
                WNBlocks.STRAWBERRY_CAKE = new CakeBase(Block.Properties.create(Material.CAKE).hardnessAndResistance(0.5F).sound(SoundType.CLOTH),new Item.Properties().group(ItemGroup.FOOD), Main.RegistryEvents.location("strawberry_cake")),
                WNBlocks.WHITE_CHOCOLATE_CAKE = new CakeBase(Block.Properties.create(Material.CAKE).hardnessAndResistance(0.5F).sound(SoundType.CLOTH),new Item.Properties().group(ItemGroup.FOOD), Main.RegistryEvents.location("white_chocolate_cake")),
                WNBlocks.YEAST_DOUGH = new CakeBase(Block.Properties.create(Material.CAKE).hardnessAndResistance(0.5F).sound(SoundType.CLOTH),new Item.Properties().group(ItemGroup.FOOD), Main.RegistryEvents.location("yeast_dough")),

                WNBlocks.COCKLESHELL = new ShellBlock(Block.Properties.create(Material.CORAL),new Item.Properties().group(Main.WILDNATURE_GROUP), Main.RegistryEvents.location("cockleshell")),
                WNBlocks.HORN_SHELL = new ShellBlock(Block.Properties.create(Material.CORAL),new Item.Properties().group(Main.WILDNATURE_GROUP), Main.RegistryEvents.location("horn_shell")),
                WNBlocks.LIONS_PAW = new ShellBlock(Block.Properties.create(Material.CORAL),new Item.Properties().group(Main.WILDNATURE_GROUP), Main.RegistryEvents.location("lions_paw")),
                WNBlocks.SAND_DOLLAR = new ShellBlock(Block.Properties.create(Material.CORAL),new Item.Properties().group(Main.WILDNATURE_GROUP), Main.RegistryEvents.location("sand_dollar")),
                WNBlocks.STAR_FISH = new ShellBlock(Block.Properties.create(Material.CORAL),new Item.Properties().group(Main.WILDNATURE_GROUP), Main.RegistryEvents.location("star_fish")),

                WNBlocks.JELLY_BLUE_BLOCK = new JellyBlock(Block.Properties.create(Material.CORAL, MaterialColor.LIGHT_BLUE_TERRACOTTA).slipperiness(0.95F).sound(SoundType.SLIME).lightValue(5),new Item.Properties().group(Main.WILDNATURE_GROUP), Main.RegistryEvents.location("jelly_blue_block")),
                WNBlocks.JELLY_ORANGE_BLOCK = new JellyBlock(Block.Properties.create(Material.CORAL, MaterialColor.ORANGE_TERRACOTTA).slipperiness(0.95F).sound(SoundType.SLIME).lightValue(9),new Item.Properties().group(Main.WILDNATURE_GROUP), Main.RegistryEvents.location("jelly_orange_block")),
                WNBlocks.JELLY_PINK_BLOCK = new JellyBlock(Block.Properties.create(Material.CORAL, MaterialColor.PINK_TERRACOTTA).slipperiness(0.95F).sound(SoundType.SLIME).lightValue(9),new Item.Properties().group(Main.WILDNATURE_GROUP), Main.RegistryEvents.location("jelly_pink_block")),
                WNBlocks.JELLY_RED_BLOCK = new JellyBlock(Block.Properties.create(Material.CORAL, MaterialColor.RED_TERRACOTTA).slipperiness(0.95F).sound(SoundType.SLIME).lightValue(7),new Item.Properties().group(Main.WILDNATURE_GROUP), Main.RegistryEvents.location("jelly_red_block")),
                WNBlocks.JELLY_WHITE_BLOCK = new JellyBlock(Block.Properties.create(Material.CORAL, MaterialColor.WHITE_TERRACOTTA).slipperiness(0.95F).sound(SoundType.SLIME).lightValue(13),new Item.Properties().group(Main.WILDNATURE_GROUP), Main.RegistryEvents.location("jelly_white_block")),

                WNBlocks.HYDROTHERMAL_VENT = new HydrothermalVent(Block.Properties.create(Material.SHULKER, MaterialColor.STONE).sound(SoundType.SCAFFOLDING),new Item.Properties().group(Main.WILDNATURE_GROUP), Main.RegistryEvents.location("hydrothermal_vent"))

        };
    }

    public Block[] getBlock() {
        return block;
    }
}
